sudo: false
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install flake8==3.7.8 pylint==2.3.1 black==19.3b0
script:
  - flake8 --exclude cast_channel_pb2.py,authority_keys_pb2.py,logging_pb2.py pychromecast
  - pylint pychromecast
  - black pychromecast --check
